# Generated by Django 5.1.5 on 2026-04-26 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_task_did_not_finish_task_finished_late_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="behavior",
            name="points_value",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_color",
            field=models.CharField(default="#6C63FF", max_length=7),
        ),
        migrations.AddField(
            model_name="customuser",
            name="parent_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reward",
            name="icon",
            field=models.CharField(default="🎁", max_length=10),
        ),
        migrations.AddField(
            model_name="reward",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("chores", "Chores"),
                    ("homework", "Homework"),
                    ("hygiene", "Hygiene"),
                    ("outdoor", "Outdoor"),
                    ("other", "Other"),
                ],
                default="chores",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="points_value",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="task",
            name="fun_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Terrible"),
                    (2, "Not Great"),
                    (3, "Okay"),
                    (4, "Fun"),
                    (5, "Amazing!"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Urgent")],
                default=2,
            ),
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("task", "Task Completion"),
                            ("behavior_positive", "Positive Behavior"),
                            ("behavior_negative", "Negative Behavior"),
                            ("redemption", "Reward Redeemed"),
                            ("bonus", "Bonus Points"),
                            ("penalty", "Penalty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="core.reward",
                    ),
                ),
            ],
        ),
    ]
