# Generated by Django 5.1.5 on 2026-05-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notifications_task_review_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_submitted', 'Task Submitted'), ('task_approved', 'Task Approved'), ('task_rejected', 'Task Needs Adjustments'), ('reward_requested', 'Reward Requested'), ('reward_approved', 'Reward Approved'), ('reward_denied', 'Reward Not This Time'), ('points_changed', 'Points Changed'), ('system', 'System')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rewardredemption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Not This Time')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Needs Adjustments')], default='assigned', max_length=12),
        ),
    ]
